services:
  db:
    container_name: vyking-db
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vyking-task
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
        - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - local

  redis:
    container_name: vyking-redis
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    restart: unless-stopped
    networks:
      - local

  backend:
    container_name: vyking-backend
    build:
      context: .
      dockerfile: deploy/tools/docker/backend/Dockerfile
    entrypoint: /backend/entrypoint.sh
    env_file:
      - deploy/tools/env/backend.dev.env
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./deploy/backend/node_modules:/backend/node_modules
      - ./deploy/backend/src:/backend/src
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
    mysql-data:
    redis-data: